"""Add seasons and episodes tables, add episode_id to watch_history

Revision ID: 4dc3be3298b6
Revises: 164a2672b0ae
Create Date: 2026-07-08 09:58:29.546534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc3be3298b6'
down_revision: Union[str, Sequence[str], None] = '164a2672b0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_history', sa.Column('episode_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'watch_history', 'episodes', ['episode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watch_history', type_='foreignkey')
    op.drop_column('watch_history', 'episode_id')
    # ### end Alembic commands ###
