"""Add trailer_url to movies

Revision ID: ae0eb3557e89
Revises: 4dc3be3298b6
Create Date: 2026-07-08 21:59:41.942303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0eb3557e89'
down_revision: Union[str, Sequence[str], None] = '4dc3be3298b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('trailer_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'trailer_url')
    # ### end Alembic commands ###
